"""
Feature-preparation utilities for ML-based optimal substation switching.

This module prepares node, edge, and target-label features for different
machine-learning models used in power-system congestion management and
busbar-splitting studies.

The implementations include:
    - GNN-ready node and edge feature construction
    - FNN-ready fixed-size line-feature construction
    - Regression and classification label generation
    - Prediction masks for candidate switching nodes
    - Custom regression loss for sign-aware learning
    - Classification metric evaluation
    - Train/validation/test splitting utilities
    - Diagnostic plotting functions for regression and classification outputs

The generated features are intended for supervised learning, graph neural
networks (GNNs), feed-forward neural networks (FNNs), and ML-assisted
topology-control studies.

"""

# Prepare GNN and FNN Features
# import numpy as np

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
from matplotlib.ticker import FormatStrFormatter
from sklearn.metrics import roc_auc_score


# %%


def Prepare_Features_GNN(
    dataset,
    gamma=10,
    ds_loading=0.0,
    Nsamples='all',
    ForceSplit=True,
    HopsFilter=1,
    Clf_threshold=0.0,
    clip_val=-1.0):
    """
    Prepare node, edge, and target-label features for GNN and FNN models.

    Input: X_pd [sample,bus],X_delta[sample,Bus], X_pg[sample,G], X_pinj[sample,bus] is injection
    X_pflow_list is a list of numpy arrays of flow values, based on the topology of the dataset
    y_pflow[sample,candidate_sw,line],
    Edge_sender_list/Edge_receiver_list: list of np vectors that contains the sender/receiver index of each sample

    X is array, x is vector

    ds_loading creates a discontinouty in the index.

    Output: a dictionary of node and edge features and lables to predict.
    node types: 'bus', --> HomoGNN means we only have one node type
    edge_type: 'line' for now.

    Parameters
    ----------
    dataset : dict
        Training dataset generated by the DC-OSS data-generation pipeline.
        It must contain flow, injection, topology, line-limit, candidate-node,
        and graph-connectivity information.
    gamma : float
        Exponent used in the congestion index.
    ds_loading : float
        Loading threshold used to activate the congestion index.
    Nsamples : int or str
        Number of samples to process. Currently kept for compatibility.
    ForceSplit : bool
        If False, negative congestion improvements are clipped to zero.
    HopsFilter : int
        Maximum hop distance from congestion for keeping candidate nodes.
    Clf_threshold : float
        Threshold used to convert regression labels into binary labels.
    clip_val : float
        Lower clipping value for regression targets.

    Returns
    -------
    Finaldict : dict
        Dictionary containing GNN/FNN features, regression labels,
        classification labels, graph connectivity, candidate-node indices,
        and prediction masks.
    """

    # Nline = len(networkdata['line'])
    # Bus=networkdata['Bus']
    # Nbus = len(Bus)

    # line_reactance = networkdata['branch1D']['x'].to_numpy()

    # === Load dataset arrays and lists
    X_pinj = dataset['X_pinj']
    X_pflow = dataset['X_pflow']
    X_pflow_list = dataset['X_pflow_list']
    y_pflow_list = dataset['y_pflow_list']
    Edge_sender_list = dataset['Edge_sender_list']
    Edge_receiver_list = dataset['Edge_receiver_list']
    line_outage_indices = dataset['line_outage_indices']
    bus_sw_indices_list = dataset['bus_sw_indices_list']
    X_node_degree = dataset['X_node_degree']
    line_limit_list = dataset['line_limit_list']
    hops_list = dataset['hops_list']

    # === Dataset dimensions
    Nbus = X_pinj.shape[1]
    line_reactance = dataset['HyperParameters']['line_reactance']
    Nline = len(line_reactance)

    Nsamples = X_pinj.shape[0]

    # print(f"{Nsamples} Samples!")

    # ==========================================================================
    # Bus/node features
    # ==========================================================================

    # create bus features
    N_bus_features = 3

    X_bus_feature = np.zeros((Nsamples, Nbus, N_bus_features))
    X_bus_feature[:, :, 0] = X_pinj                 # feature 0 is injection
    X_bus_feature[:, :, 1] = X_node_degree          # feature 1 is degree
    X_bus_feature[:, :, 2] = np.array(hops_list)    # hops away


    # ==========================================================================
    # Edge/line features for GNN models
    # ==========================================================================

    # create edge/line features
    N_line_features = 4

    X_line_feature_list = []   # a list of [Nline,N_line_features] #np.zeros((Nsamples,Nline,N_line_features))

    for sample in range(Nsamples):
        nl = Nline - len(line_outage_indices[sample])
        x_line_feature = np.zeros((nl, N_line_features))

        x_line_feature[:, 0] = X_pflow_list[sample]
        x_line_feature[:, 1] = X_pflow_list[sample] / line_limit_list[sample]     # ratio
        x_line_feature[:, 2] = line_limit_list[sample]                            # limit
        x_line_feature[:, 3] = np.delete(line_reactance, line_outage_indices[sample])   # reactance

        X_line_feature_list += [x_line_feature]

    # ==========================================================================
    # Fixed-size line features for FNN models
    # ==========================================================================

    # X_line_feature_FNN
    X_line_feature_FNN = np.zeros((Nsamples, Nline, 4))
    X_line_feature_FNN[:, :, 0] = X_pflow
    X_line_feature_FNN[:, :, 3] = np.tile(line_reactance, (Nsamples, 1))   # reactance

    for sample in range(Nsamples):
        ll = 0

        for l in range(Nline):

            if l not in line_outage_indices[sample]:
                X_line_feature_FNN[sample, l, 1] = X_line_feature_list[sample][ll, 1]   # ratio
                X_line_feature_FNN[sample, l, 2] = X_line_feature_list[sample][ll, 2]   # limit
                ll += 1

    # ==========================================================================
    # Initial congestion index
    # ==========================================================================

    # index
    X_pratio = X_line_feature_FNN[:, :, 1]   # X_pflow/x_limit         #Xratio can be an input feature

    overloaded_mask = np.abs(X_pratio) > ds_loading
    congestion_index = np.sum(((np.abs(X_pratio)) ** gamma) * overloaded_mask, axis=1)

    obj_ini = congestion_index   # [sample]

    # ==========================================================================
    # Final congestion index after candidate splitting
    # ==========================================================================

    obj_fin_list = []

    for sample in range(Nsamples):
        y_pratio = y_pflow_list[sample] / line_limit_list[sample]
        overloaded_mask = np.abs(y_pratio) > ds_loading   # [num_sw, nline]
        congestion_index = np.sum(
            ((np.abs(y_pratio)) ** gamma) * overloaded_mask,
            axis=1,
        )   # [num_sw]
        obj_fin_list.append(congestion_index)

    # ==========================================================================
    # Regression target generation
    # ==========================================================================

    delta_obj_list = []

    # clip_val = -1
    for i in range(Nsamples):
        delta = obj_ini[i] - obj_fin_list[i]   # obj_ini[i]: scalar, obj_fin_list[i]: [num_sw_i]
        if ForceSplit == False:
            delta[delta < 0] = 0   # remove negative values if needed
        # Clip values
        delta_clipped = np.clip(delta, a_min=clip_val, a_max=1000)   # [num_sw_i]
        # Reshape to [num_sw_i, 1] and store
        delta_obj_list.append(delta_clipped.reshape(-1, 1))

    Y_reg_list = delta_obj_list

    # ==========================================================================
    # Candidate-node filtering
    # ==========================================================================
    # filtering
    Y_reg_filtered = []
    bus_sw_indices_filtered = []

    for i in range(Nsamples):
        values = []
        indices = []
        for sw_ind, sw in enumerate(bus_sw_indices_list[i]):
            val = Y_reg_list[i][sw_ind]
            if 0 <= hops_list[i][sw] <= HopsFilter:   # filtering bad data
                values.append(val)
                indices.append(sw)
        Y_reg_filtered.append(np.array(values))
        bus_sw_indices_filtered.append(indices)
    Y_reg_list = Y_reg_filtered
    bus_sw_indices_list = bus_sw_indices_filtered

    # ==========================================================================
    # Classification labels
    # ==========================================================================

    # classification labels pos:good, neg:bad
    Y_clf_list = [(y > Clf_threshold).astype(np.int64) for y in Y_reg_list]

    # ==========================================================================
    # Homogeneous GNN target tensors and prediction mask
    # ==========================================================================

    # homo data
    Y_reg_homo = np.zeros((Nsamples, Nbus, 1))
    Y_clf_homo = np.zeros((Nsamples, Nbus, 1))
    prediction_mask = np.zeros((Nsamples, Nbus), dtype=bool)

    for s in range(Nsamples):
        for i, node_idx in enumerate(bus_sw_indices_list[s]):   # bus_sw_indices_list is a list of lists
            Y_reg_homo[s, node_idx, 0] = Y_reg_list[s][i, 0]
            Y_clf_homo[s, node_idx, 0] = Y_clf_list[s][i, 0]
            prediction_mask[s, node_idx] = True

    # ==========================================================================
    # Output dictionary
    # ==========================================================================

    # FinalDict
    Finaldict = {}

    Finaldict['X_bus_feature'] = X_bus_feature                 # [sample,bus,features]
    Finaldict['X_bus_sw_feature'] = X_bus_feature
    Finaldict['Y_reg_homo'] = Y_reg_homo
    Finaldict['Y_clf_homo'] = Y_clf_homo
    Finaldict['Y_reg_list'] = Y_reg_list
    Finaldict['Y_clf_list'] = Y_clf_list
    Finaldict['X_line_feature_list'] = X_line_feature_list     # list of [nline,N_line_features]
    Finaldict['X_line_feature_FNN'] = X_line_feature_FNN       # I use this for FNN
    Finaldict['Edge_sender_list'] = Edge_sender_list
    Finaldict['Edge_receiver_list'] = Edge_receiver_list
    Finaldict['bus_sw_indices_list'] = bus_sw_indices_list     # this is used for masking or node types
    Finaldict['prediction_mask'] = prediction_mask
    return Finaldict


# %%
class BoundaryAwareRegressionLoss(nn.Module):
    """
    Sign-aware regression loss for congestion-reduction prediction.

    This loss combines SmoothL1 regression loss with an optional penalty for
    sign mismatch between model outputs and targets. It can also assign higher
    weight to positive targets, which is useful when positive congestion
    reduction actions are more important than neutral or negative actions.

    Parameters
    ----------
    penalty_weight : float
        Weight applied to the sign-mismatch penalty.
    pos_weight : float
        Additional weight applied to positive regression targets.
    """

    def __init__(
        self,
        penalty_weight=0.0,
        pos_weight=0.0,
    ):
        """
        Initialize the boundary-aware regression loss.

        Parameters
        ----------
        penalty_weight : float
            Weight applied to the sign-mismatch penalty term.
        pos_weight : float
            Weight applied to samples with positive targets.
        """

        super().__init__()

        self.mse = nn.SmoothL1Loss()   # nn.MSELoss()
        self.penalty_weight = penalty_weight
        self.pos_weight = pos_weight   # how much more to weight positive targets

    def forward(
        self,
        outputs,
        targets,
    ):
        """
        Compute the weighted regression loss and sign-mismatch penalty.

        Parameters
        ----------
        outputs : torch.Tensor
            Model-predicted regression outputs.
        targets : torch.Tensor
            Ground-truth regression targets.

        Returns
        -------
        total_loss : torch.Tensor
            Combined regression and sign-mismatch loss.
        """

        # MSE loss
        base_loss = self.mse(outputs, targets)

        # Weight the regression loss based on the sign of the target
        # 1 if target ≤ 0, pos_weight if target > 0
        weights = torch.where(targets > 0, self.pos_weight, 1.0)

        weighted_loss = (base_loss * weights).mean()

        # Calculate sign mismatch:
        # When sign(outputs) != sign(targets) --> penalty applies
        sign_outputs = torch.sign(outputs)
        sign_targets = torch.sign(targets)

        # mismatch_mask = 1 where signs disagree, 0 where agree or zero target
        mismatch_mask = (sign_outputs != sign_targets).float()

        # Only penalize where target != 0 to avoid undefined sign issues #TODO?
        nonzero_target_mask = (targets != 0).float()

        penalty_mask = mismatch_mask * nonzero_target_mask

        # Penalty is proportional to magnitude of the prediction error where sign mismatch occurs
        penalty = (torch.abs(outputs - targets) * penalty_mask).mean()

        # Total loss = regression loss + weighted penalty for sign mismatch
        total_loss = weighted_loss + self.penalty_weight * penalty

        return total_loss


# %%

def classification_metrics(
    preds,
    targets,
    probs=None,
    normalize=True
):
    """
    Compute binary classification metrics.

    Compute classification metrics including TP, TN, FP, FN, Accuracy,
    Precision, Recall, and F1 Score.
    Optionally normalize TP, TN, FP, FN to percentages.

    Args:
        preds (torch.Tensor): Binary predictions (0 or 1).
        targets (torch.Tensor): Ground truth binary labels (0 or 1).
        probs (torch.Tensor, optional): Predicted probabilities for positive class (0.0–1.0), for AUC calculation.
        normalize (bool): If True, TP, TN, FP, FN will be reported as percentages.

    Parameters
    ----------
    preds : torch.Tensor
        Binary predictions, typically thresholded to 0 or 1.
    targets : torch.Tensor
        Ground-truth binary labels.
    probs : torch.Tensor, optional
        Predicted probabilities for the positive class. Used for AUC.
    normalize : bool
        If True, report TP, TN, FP, and FN as percentages.

    Returns
    -------
    metrics : dict
        Dictionary of computed classification metrics.
    """

    # Apply sigmoid and threshold

    preds_bin = preds.detach().cpu().int()   # Assumes preds already thresholded #(torch.sigmoid(preds) > 0.5).int()
    targets = targets.detach().cpu().int()

    # === Confusion-matrix counts
    TP = ((preds_bin == 1) & (targets == 1)).sum().item()
    TN = ((preds_bin == 0) & (targets == 0)).sum().item()
    FP = ((preds_bin == 1) & (targets == 0)).sum().item()
    FN = ((preds_bin == 0) & (targets == 1)).sum().item()

    total = TP + TN + FP + FN

    # === Metrics
    metrics = {
        'TP': TP,
        'TN': TN,
        'FP': FP,
        'FN': FN,
        'Accuracy': (TP + TN) / total if total > 0 else 0,
        'Precision': TP / (TP + FP) if (TP + FP) > 0 else 0,
        'Recall': TP / (TP + FN) if (TP + FN) > 0 else 0,
        'F1 Score': 2 * TP / (2 * TP + FP + FN) if (2 * TP + FP + FN) > 0 else 0,
    }

    # Optionally add AUC if probabilities are provided
    if probs is not None:
        try:
            probs = probs.detach().cpu()
            metrics['AUC'] = float(roc_auc_score(targets.numpy(), probs.numpy()))
        except:
            metrics['AUC'] = float('nan')

    if normalize:
        # Convert counts to percentages of total
        for key in ['TP', 'TN', 'FP', 'FN']:
            metrics[f'{key} (%)'] = 100 * metrics[key] / total if total > 0 else 0
            del metrics[key]

    return metrics


# %%

def train_val_test_split(
    num_samples=10000,
    split_ratios=[0.7, 0.15, 0.15],
    seed=0):
    """
    Split sample indices into training, validation, and test subsets.

    Parameters
    ----------
    num_samples : int
        Total number of samples.
    split_ratios : list
        Three-element list containing train, validation, and test ratios.
    seed : int
        Random seed used for reproducible shuffling.

    Returns
    -------
    train_indices : torch.Tensor
        Indices assigned to the training set.
    val_indices : torch.Tensor
        Indices assigned to the validation set.
    test_indices : torch.Tensor
        Indices assigned to the test set.
    """

    train_ratio = split_ratios[0]
    val_ratio = split_ratios[1]
    test_ratio = split_ratios[2]

    # Set random seed for reproducibility
    torch.manual_seed(seed)

    # Shuffle indices
    indices = torch.randperm(num_samples)

    # Compute split sizes
    train_size = int(train_ratio * num_samples)
    val_size = int(val_ratio * num_samples)

    # Split indices
    train_indices = indices[:train_size]
    val_indices = indices[train_size:train_size + val_size]
    test_indices = indices[train_size + val_size:]

    return train_indices, val_indices, test_indices


# %%

def plot_prediction_scatter_reg(
    pred,
    target):
    """
    Plot regression predictions against target values.

    Scatter plot of predictions vs targets with color indicating MSE error.

    Args:
        pred (array-like): Predicted values.
        target (array-like): Ground truth target values.

    Parameters
    ----------
    pred : array-like
        Predicted regression values.
    target : array-like
        Ground-truth regression values.
    """

    # Compute squared error for coloring
    mse_error = (pred - target) ** 2

    print("mse error is: %.5f " % np.mean(mse_error))

    # Scatter plot
    plt.figure(figsize=(5, 4))

    scatter = plt.scatter(
        target,
        pred,
        c=mse_error,
        cmap='coolwarm',
        alpha=0.5,
        s=5,
    )

    cbar = plt.colorbar(scatter)
    cbar.set_label('Squared Error')
    cbar.ax.yaxis.set_major_formatter(FormatStrFormatter('%.2f'))

    # Reference lines
    min_val = min(target.min(), pred.min())
    max_val = max(target.max(), pred.max())

    plt.plot([min_val, max_val], [min_val, max_val], 'k--', label='y = x')   # y = x line
    plt.axhline(0, color='gray', linestyle='--')                             # y = 0
    plt.axvline(0, color='gray', linestyle='--')                             # x = 0

    plt.xlabel('Target')
    plt.ylabel('Prediction')
    plt.title('Prediction vs Target with Error Coloring')

    # plt.legend()

    plt.grid(True)
    plt.tight_layout()
    plt.show()


def plot_prediction_scatter_clf(
    prob,
    target_reg,
    target_binary):
    """
    Plot classifier probabilities against regression targets.

    Scatter plot of predictions vs targets with color indicating MSE error.

    Args:
        pred (array-like): Predicted values.
        target (array-like): Ground truth target values.

    Parameters
    ----------
    prob : array-like
        Predicted probabilities for the positive class.
    target_reg : array-like
        Regression target values used on the x-axis.
    target_binary : array-like
        Binary classification labels used to compute probability error.
    """

    # Compute squared error for coloring
    mse_error = (prob - target_binary) ** 2

    print("mse error is: %.5f " % np.mean(mse_error))

    # Scatter plot
    plt.figure(figsize=(5, 4))

    scatter = plt.scatter(
        target_reg,
        prob,
        c=mse_error,
        cmap='coolwarm',
        alpha=0.5,
        s=5)

    cbar = plt.colorbar(scatter)
    cbar.set_label('Squared Error')
    cbar.ax.yaxis.set_major_formatter(FormatStrFormatter('%.2f'))

    # Reference lines
    # min_val = min(target.min(), pred.min())
    # max_val = max(target.max(), pred.max())
    # plt.plot([min_val, max_val], [min_val, max_val], 'k--', label='y = x')  # y = x line

    plt.axhline(0, color='gray', linestyle='--')   # y = 0
    plt.axvline(0, color='gray', linestyle='--')   # x = 0
    plt.xlabel('Target')
    plt.ylabel('Prediction')
    plt.title('Prediction vs Target with Error Coloring')
    # plt.legend()

    plt.grid(True)
    plt.tight_layout()
    plt.show()


def signed_root(x, root=2):
    x = np.array(x)  # ensure input is an array
    signs = np.sign(x)
    return (np.abs(x)) ** (1 / root) * signs
